# ===============================================
# Phantom Daemon - Traps Manifest
# ===============================================
# Этот файл описывает, какие файлы-ловушки и где нужно развернуть.
# 'id' - уникальный идентификатор для корреляции в логах.
# 'template' - имя файла-шаблона в папке resources/templates.
# 'output' - имя файла, которое увидит злоумышленник.
# 'category' - тип ловушки (для логики реагирования).
# 'format' - 'text' (будет обработан Jinja2) или 'binary' (будет скопирован).
# 'priority' - важность ловушки для SOC.

traps:
  - id: trap-db-prod-01
    template: prod_db_config.json.j2
    output: db_production.json
    category: credential
    format: text
    priority: critical

  - id: trap-aws-root-01
    template: aws_credentials.txt.j2
    output: .aws/credentials # Скрытый файл, классика
    category: credential
    format: text
    priority: critical

  - id: trap-vpn-corp-01
    template: vpn_client.ovpn.j2
    output: corporate_vpn.ovpn
    category: config
    format: text
    priority: medium

  - id: trap-ssh-key-01
    template: id_rsa.j2
    output: .ssh/id_rsa # Скрытый SSH-ключ
    category: credential
    format: text
    priority: high

  - id: trap-doc-finance-01
    template: payroll.docx
    output: Зарплатная_ведомость_Q4_2024.docx
    category: document
    format: binary
    priority: high

  - id: trap-xls-pass-01
    template: passwords.xlsx
    output: Учетные_данные_серверов.xlsx
    category: document
    format: binary
    priority: critical